name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: npm i -g yarn
      - run: yarn
      - run: USE_SSH=true npm run deploy 
