name: Test build on Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    name: Test build on PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Test build
        run: |
          yarn install --frozen-lockfile
          yarn build
